version: "2.3"

services:
    base:
        image: yolo:0.1
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: yolo-base
        hostname: yolo
        ipc: host
        runtime: nvidia
        volumes:
            - $PWD:/workspace
            - /mnt/data:/mnt/data
            - /media:/media
        environment:
            - DEBUG_COLORS="true"
            - TERM=xterm-256color
            - COLORTERM=truecolor

    dev:
        container_name: yolo-dev
        extends:
            service: base
        ports:
            - ${PORT:-6006}:${PORT:-6006}
        stdin_open: true
        tty: true
